# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88dbaa16c05c41800c29254bb161a2e236e1d3ee44da050120b236bdd356737c905d044f053b675ba44d168a3457519bac445965145fa66988b4687c0f23e902

test:
  secret_key_base: 84dbd3399f0c3ba3d4605b94d2fa4ec29a9bf9b1d7b271496e929a06a2a29cc0b3d8d9c8b740b5077df7564642b38010f062dc95241259c0591a558072a0fedf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
